Repository ximing21/207-Group, pull requests merged in 2023-11, with the labels that each got.

#10 Ximing: Finished implementation of GetTaskUseCase
  src/api/TodoistDB.java
  src/app/AddProjectUseCaseFactory.java
  src/app/GetTaskUseCaseFactory.java
  src/app/Main.java
  src/entity/Project.java
  src/entity/Statistics.java
  src/entity/Task.java
  src/entity/TaskInterface.java
  src/interface_adapter/add_project/AddProjectPresenter.java
  src/interface_adapter/added_project/AddedProjectViewModel.java
  src/interface_adapter/get_task/GetTaskController.java
  src/interface_adapter/get_task/GetTaskPresenter.java
  src/interface_adapter/get_task/GetTaskState.java
  src/interface_adapter/get_task/GetTaskViewModel.java
  src/use_case/get_task/GetTaskDataAccessInterface.java
  src/use_case/get_task/GetTaskInteractor.java
  src/use_case/get_task/GetTaskOutputData.java
  src/view/AddProjectView.java
  src/view/GetTaskView.java
  target/classes/api/TodoistDB.class
  target/classes/app/AddProjectUseCaseFactory.class
  target/classes/app/Main.class
  target/classes/entity/Project.class
  target/classes/entity/Statistics.class
  target/classes/entity/Task.class
  target/classes/entity/TaskInterface.class
  target/classes/interface_adapter/add_project/AddProjectPresenter.class
  target/classes/view/AddProjectView.class
Labels: enhancement

#12 [Xuanyi Lyu] Added use case for closing tasks.
  .idea/misc.xml
  .idea/uiDesigner.xml
  src/api/TodoistDB.java
  src/app/GetTaskUseCaseFactory.java
  src/app/Main.java
  src/entity/Task.java
  src/interface_adapter/add_task/AddTask.java
  src/interface_adapter/add_task/AddTaskController.java
  src/interface_adapter/add_task/AddTaskPresenter.java
  src/interface_adapter/close_task/CloseTaskController.java
  src/interface_adapter/close_task/CloseTaskPresenter.java
  src/interface_adapter/close_task/CloseTaskState.java
  src/interface_adapter/close_task/CloseTaskViewModel.java
  src/use_case/add_task/AddTaskDataAccessInterface.java
  src/use_case/add_task/AddTaskInputBoundary.java
  src/use_case/add_task/AddTaskInputData.java
  src/use_case/add_task/AddTaskInteractor.java
  src/use_case/add_task/AddTaskOutputBoundary.java
  src/use_case/add_task/AddTaskOutputData.java
  src/use_case/close_task/CloseTaskDataAccessInterface.java
  src/use_case/close_task/CloseTaskInputBoundary.java
  src/use_case/close_task/CloseTaskInputData.java
  src/use_case/close_task/CloseTaskInteractor.java
  src/use_case/close_task/CloseTaskOutputBoundary.java
  src/use_case/close_task/CloseTaskOutputData.java
  src/view/GetTaskView.java
  target/classes/api/TodoistDB.class
  target/classes/app/Main.class
  target/classes/view/AddProjectView.class
Labels: enhancement

#13 [Xuanyi Lyu] Complete most of the add task use case
  src/api/TodoistDB.java
  src/app/GetTaskUseCaseFactory.java
  src/interface_adapter/add_task/AddTaskController.java
  src/interface_adapter/add_task/AddTaskPresenter.java
  src/interface_adapter/get_task/GetTaskPresenter.java
  src/interface_adapter/get_task/GetTaskViewModel.java
  src/use_case/add_task/AddTaskDataAccessInterface.java
  src/use_case/add_task/AddTaskInputBoundary.java
  src/use_case/add_task/AddTaskInputData.java
  src/use_case/add_task/AddTaskInteractor.java
  src/use_case/add_task/AddTaskOutputBoundary.java
  src/view/GetTaskView.java
  target/classes/api/TodoistDB.class
  target/classes/app/Main.class
  target/classes/entity/Task.class
  target/classes/interface_adapter/add_task/AddTask.class
  target/classes/interface_adapter/add_task/AddTaskController.class
Labels: bug, Enhancement, New Feature

#14 [Xuanyi Lyu] Complete most of the add task use case
  src/interface_adapter/add_task/AddTaskPresenter.java
  src/interface_adapter/add_task/AddTaskState.java
  src/interface_adapter/add_task/AddTaskViewModel.java
  src/view/GetTaskView.java
Labels: Enhancement, New Feature

#16 [Xuanyi Lyu]Added use case for adding tasks.
  src/api/TodoistDB.java
  src/interface_adapter/add_task/AddTaskPresenter.java
  src/interface_adapter/add_task/AddTaskState.java
  src/use_case/add_task/AddTaskDataAccessInterface.java
  src/use_case/add_task/AddTaskInteractor.java
  src/use_case/add_task/AddTaskOutputData.java
  src/view/GetTaskView.java
  target/classes/api/TodoistDB.class
  target/classes/interface_adapter/add_task/AddTaskState.class
  target/classes/interface_adapter/add_task/AddTaskViewModel.class
Labels: Enhancement, New Feature

#23 [Xuanyi Lyu]Add deadline feature
  src/api/TodoistDB.java
  src/entity/Task.java
  src/interface_adapter/add_task/AddTaskController.java
  src/interface_adapter/add_task/AddTaskPresenter.java
  src/interface_adapter/add_task/AddTaskState.java
  src/use_case/add_task/AddTaskDataAccessInterface.java
  src/use_case/add_task/AddTaskInteractor.java
  src/use_case/add_task/AddTaskOutputData.java
  src/view/GetTaskView.java
Labels: Enhancement, New Feature

#26 [Xuanyi Lyu] Fixed the error generated when deleting a project.
  src/view/AddProjectView.java
Labels: Enhancement, BugFix

#28 Ximing: Implemented new feature for GetTaskUseCase
  README.md
  src/app/GetTaskUseCaseFactory.java
  src/interface_adapter/close_task/CloseTaskPresenter.java
  src/interface_adapter/close_task/CloseTaskState.java
  src/interface_adapter/get_task/GetTaskPresenter.java
  src/interface_adapter/get_task/GetTaskState.java
  src/use_case/close_task/CloseTaskDataAccessInterface.java
  src/use_case/close_task/CloseTaskInteractor.java
  src/use_case/close_task/CloseTaskOutputBoundary.java
  src/use_case/close_task/CloseTaskOutputData.java
  src/use_case/get_task/GetTaskDataAccessInterface.java
  src/use_case/get_task/GetTaskInteractor.java
  src/use_case/get_task/GetTaskOutputData.java
  src/view/GetTaskView.java
  target/classes/api/TodolistDB.class
  target/classes/app/Main.class
  target/classes/interface_adapter/close_task/CloseTaskPresenter.class
  target/classes/interface_adapter/get_task/GetTaskPresenter.class
  target/classes/interface_adapter/get_task/GetTaskState.class
  target/classes/use_case/close_task/CloseTaskInteractor.class
  target/classes/use_case/close_task/CloseTaskOutputData.class
  target/classes/use_case/get_task/GetTaskDataAccessInterface.class
  target/classes/use_case/get_task/GetTaskInteractor.class
  target/classes/use_case/get_task/GetTaskOutputData.class
  target/classes/view/GetTaskView$1.class
  target/classes/view/GetTaskView$2.class
  target/classes/view/GetTaskView.class
Labels: Enhancement, New Feature

#30 Fixed bug related to GetTaskUseCase
  emotional_phrases
  src/interface_adapter/switch_view/SwitchViewPresenter.java
  src/view/GetTaskView.java
  target/classes/view/GetTaskView$1.class
  target/classes/view/GetTaskView$2.class
  target/classes/view/GetTaskView.class
Labels: BugFix

#35 [Xuanyi Lyu] Optimize the logic of deleting projects.
  src/interface_adapter/delete_project/DeleteProjectPresenter.java
  src/use_case/delete_project/DeleteProjectDataAccessInterface.java
  src/use_case/delete_project/DeleteProjectInteractor.java
  src/use_case/delete_project/DeleteProjectOutputData.java
  src/view/AddProjectView.java
Labels: Enhancement, BugFix

#43 [Xuanyi Lyu] Fixed regex issue for date format
  src/view/GetTaskView.java
Labels: Enhancement, BugFix

#46 [Xuanyi Lyu] Update emotional_phrases
  emotional_phrases
  src/api/TodoistDB.java
  src/app/Main.java
  src/entity/Project.java
  src/entity/ProjectFactory.java
  src/entity/Task.java
  src/interface_adapter/add_project/AddProjectViewModel.java
  src/interface_adapter/get_task/GetTaskViewModel.java
  src/view/GetTaskView.java
  src/view/ViewManager.java
Labels: Enhancement

#47 [Xuanyi Lyu] Trying to add a test case.
  Project.iml
  Test/GetProjectTest.java
  Test/app/AddProjectUseCaseFactoryTest.java
  Test/entity/ProjectTest.java
  Test/entity/TaskTest.java
  Test/use_case/GetProjectPresenterTest.java
  Test/view/AddProjectViewTest.java
  Test/view/GetTaskViewTest.java
  pom.xml
  src/view/AddProjectView.java
  src/view/GetTaskView.java
Labels: Enhancement, TestCase

#49 Decrease lag and increase efficiency of program in general.
  src/interface_adapter/close_task/CloseTaskState.java
  src/interface_adapter/delete_project/DeleteProjectState.java
  src/interface_adapter/get_all_projects/GetProjectState.java
  src/interface_adapter/get_task/GetTaskController.java
  src/use_case/add_task/AddTaskDataAccessInterface.java
  src/use_case/add_task/AddTaskInputBoundary.java
  src/use_case/add_task/AddTaskInteractor.java
  src/use_case/add_task/AddTaskOutputBoundary.java
  src/use_case/close_task/CloseTaskDataAccessInterface.java
  src/use_case/close_task/CloseTaskInputData.java
  src/use_case/close_task/CloseTaskOutputData.java
  src/use_case/delete_project/DeleteProjectDataAccessInterface.java
  src/use_case/delete_project/DeleteProjectInteractor.java
  src/use_case/delete_project/DeleteProjectOutputData.java
  src/use_case/get_all_projects/GetProjectInputData.java
  src/use_case/get_task/GetTaskDataAccessInterface.java
  src/use_case/get_task/GetTaskInputBoundary.java
  src/use_case/get_task/GetTaskInteractor.java
Labels: Enhancement

#50 [Xuanyi Lyu] Delete pointless api interface
  src/api/TodolistDB.java
Labels: Enhancement

#52 [Xuanyi Lyu] Add gitignore.txt
  gitignore.txt
Labels: Documentation

#51 Added AddProject Test cases
  .gitignore
  Test/use_case/AddProjectTest.java
  src/api/TodoistDB.java
  src/view/Itr.java
  target/classes/api/TodoistDB$1.class
  target/classes/api/TodoistDB.class
  target/classes/app/Main.class
  target/classes/entity/Project$ProjectBuilder.class
  target/classes/entity/Project.class
  target/classes/entity/ProjectFactory.class
  target/classes/entity/Task$TaskBuilder.class
  target/classes/entity/Task.class
  target/classes/interface_adapter/add_project/AddProjectViewModel.class
  target/classes/interface_adapter/get_all_projects/GetProjectController.class
  target/classes/interface_adapter/get_all_projects/GetProjectPresenter.class
  target/classes/interface_adapter/get_task/GetTaskPresenter.class
  target/classes/interface_adapter/get_task/GetTaskViewModel.class
  target/classes/view/AddProjectView$2.class
  target/classes/view/AddProjectView$3.class
  target/classes/view/AddProjectView$4.class
  target/classes/view/AddProjectView$5.class
  target/classes/view/AddProjectView.class
  target/classes/view/GetTaskView$1.class
  target/classes/view/GetTaskView$2.class
  target/classes/view/GetTaskView.class
  target/classes/view/ViewManager.class
Labels: TestCase

#53 [Xuanyi Lyu] Modify gitignore.txt
  .gitignore
  gitignore.txt
Labels: Documentation
